version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat compileJava compileTestJava --info --no-daemon

test_script:
  - choco install docker-compose
  - gradlew.bat test windowsSmokeTest --info --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

image: Windows Server 2016

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true


