version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat compile --info --no-daemon

test_script:
  - gradlew.bat dependencies --info --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true


